### ISSUE TITLE
simplify device creation step [minor - post publish]

### ISSUE THREAD

**Issue by ptone** [Kcr19/community#13]
This step in the doc:

ssh root@$DEVICE_IP openssl rsa -in /var/lib/mender/mender-agent.pem -pubout  -out /var/lib/mender/rsa_public.pem

*could* be performed by the activation agent, reducing one step where you have to enter PW

**Comment by drewmoseley** [comment]
Or we could update the script that creates mender-agent.pem in the first place.

**Comment by drewmoseley** [comment]
This is available in #17
